- package-lock.json
- src/__tests__/profileStore-test.js
- src/profileStore.js
> better error handling

- README.md
- src/3box.js
I just needed to add documentation to the close and logout methods.
> Add documentation to close and logout methods

- KEY-USAGE.md
Feel free to place them on a different location, wasn't sure the best place to add those keys.
> Add keys used by attestari.me

- package.json
This is not released yet. Once merged do:
```sh
$ git checkout develop
$ npm run build
$ npm publish
$ git tag v1.0.0-beta-8
$ git push --tags
```
> Prep 1.0.0 beta 8

- package-lock.json
- package.json
- webpack.config.js
browserify to webpack (will allow more control over build issues)
es5 web build output
Minified output, results in error we likely will not be able to resolve. And since webpack makes the dist 3 mb large than browserify, it is not worth merging at the moment
> build: to webpack, add babel, min output

- README.md
- src/3box.js
Updated the getProfile function comments and regenerated `README.md`.
> Add missing opts to getProfile function docs

- src/3box.js
- src/__tests__/3box.test.js
This PR requires an update to the pinning-server, so we should not merge this before https://github.com/uport-project/3box-pinning-server/pull/7 has been merged and deployed.
> Switch to orbit-db-pubsub for messaging to pinning node

- src/3box.js
Didn't compare times yet, but looks to be very small, nonetheless, helps generalize some our own handling all these events. Also don't quite understand when the the replicated event is pushed, comment left in code (and commented code).
> ref: sync DBs as soon as known

- src/3box.js
I had to spin up a different pinning server (see the core channel for details)
> new pinning server id

- src/__tests__/testUtils.js
This was way easier than I expected. Was just an error in the config.
> Tests now run locally

- example/index.js
- src/3box.js
- src/__mocks__/keyValueStore.js
- src/__tests__/3box.test.js
- src/__tests__/keyValueStore.test.js
- src/__tests__/testUtils.js
- src/keyValueStore.js
- src/publicStore.js
Need to try a different approach here, create root address, then can't determine if first time from root address, luckily new pubsub responses can be used, but then this is just slower most of the time. So need think about further and reorg. Will pick up tmrrw again
> feat: use new pubsub response, dont wait for root address

- src/3box.js
- src/__tests__/3box.test.js
This PR adds code to publish the users DID to the public profile. This is makes it easier to verify users in various ways.
> Now published did to public profile if not there already

- package-lock.json
- package.json
- src/3box.js
- src/__tests__/3box.test.js
- src/__tests__/verifications.test.js
- src/utils/index.js
- src/utils/verifier.js
This should be simple enough. Please test locally with example for various scenarios of how the address-server is used.
> feat: use fetch

- example/index.html
- example/index.js
For some reason https://3box.github.io/3box-js/example/ is getting "Box is not defined". This should fix it.
> Updated example to work on github pages

- src/3box.js
> getVerifiedAccounts does not throw if there isn't a proof_did present

- src/3box.js
This fixes, where you openBox, close and then try to open again, now onsyncdone is called both times. 
This was the minimal code fix but after looking into it more it looks like ipfs/pubsub with multiple instances causes some issues, I think @oed  has mentioned this before. So there could be some issues around caching in these instances that cause pubsub to not send any messages and for onsyncdone to not be returned. I might makes sense to generally use the global ipfs/orbitdb and not close them, just keep open and then connect if already available. 
Seem likes ipfs was caching something, since peers were listed before onNewPeer was even called once. And then anytime you tried to create a new pubSub (after one was already created on an instance) it would look like its available but then …
> fix: close ipfs, so reopen works

- README.md
- readme-template.md
- src/3box.js
- src/keyValueStore.js
- src/space.js
* Added documentation for spaces
* Fixed some incorrect documentation
Please see if I should add anything more or edit any language.
> docs: add jsdoc and describe usage of spaces

- README.md
- readme-template.md
- src/3box.js
- src/api.js
> ref(api): Move getVerifiedAccounts to api

- src/utils/index.js
BOOM offchain profiles with personal_sign and no metamask!
> Fortmatic integration via ethereum.sendAsync payload id and jsonrpc key

- src/3box.js
- src/api.js
This PR adds functions to the api module for calling the new spaces REST api endpoints. See [this PR](https://github.com/3box/3box-pinning-server/pull/87)
> feat(api): Add support to query the public space data api

- src/3id/__tests__/3id.test.js
- src/3id/index.js
Marked do not merge until done following up, with fix, same stores are derived in trust wallet now, but seeing other issues (might be with state there already)
> fix: 3id serialize normalized address

- README.md
- readme-template.md
Migrating the changes I made to the raw readme to here.
> Update readme template

- README.md
- readme-template.md
Again with the uport-project move... ;-)
> README / uport-project -> 3box

- package-lock.json
- src/3box.js
- src/__tests__/3box.test.js
- src/__tests__/publicStore.test.js
- src/publicStore.js
The `_linkProfile` function should not be called when we set values from the `_linkProfile` function. Also moved the `did_proof` to before we make the http request to the address server.
> fix(3box): Ensure that linkProfile only happens once

- package.json
> uport-project -> 3box

- src/__mocks__/keyValueStore.js
- src/__tests__/keyValueStore.test.js
- src/__tests__/privateStore.test.js
- src/__tests__/space.test.js
- src/keyValueStore.js
- src/privateStore.js
- src/space.js
> Optional metadata param for get and all store methods

- README.md
- src/__tests__/thread.test.js
- src/thread.js
user friendly api for AC member/moderator updates
> feat: add onNewCapabilities fn for AC updates

- package-lock.json
- package.json
- src/__tests__/__snapshots__/space.test.js.snap
- src/__tests__/space.test.js
- src/space.js
- src/thread.js
Puts the subDIDs in the root-store entry that also has the space odbAddress. Also adding a `type` to the root-store entry.
> feat(space): add subDID to root-store entry

- src/utils/index.js
This PR adds support for the web3 1.0 http provider
> Support old and new web3 providers

- CONTRIBUTING.md
Just added a simple checklist so that we don't forget anything when releasing. Let me know if it's missing anything, or if something should be changed.
> chore: add release checklist

- src/3box.js
Closed a different, identical PR bc of a weird commit history. 
@oed I'm sure this is a pretty naive approach to the race condition issue, but it seems to do the trick for me. I'll check with another dev on the team who was also experiencing hanging calls to see if it fixes it for him too and update here.
Would love to get a fix for this issue in to a version <1.10 because I want to avoid this issue
Please let me know your thoughts! Thank you
> naive fix for #534

- CONTRIBUTING.md
- README.md
Just a small update to the release checklist
> chore: update release checklist

- .circleci/config.yml
- README.md
- package-lock.json
- package.json
- src/3box.js
- src/3id/__tests__/3id.test.js
- src/3id/__tests__/__snapshots__/3id.test.js.snap
- src/3id/index.js
- src/3id/keyring.js
- src/__mocks__/3ID.js
- src/__mocks__/keyValueStore.js
- src/__tests__/3box.test.js
- src/__tests__/keyValueStore.test.js
- src/__tests__/privateStore.test.js
- src/__tests__/space.test.js
- src/keyValueStore.js
- src/privateStore.js
- src/space.js
- src/utils/index.js
Breaking change: KeyValueStore.log is now an async function and not a property
> Simple IdentityWallet support in ThreeId class

- .gitignore
- README.md
- package-lock.json
- package.json
- src/3box.js
- src/3id/__tests__/__snapshots__/3id.test.js.snap
- src/__tests__/3box.test.js
- src/__tests__/idWallet.integration.js
- src/__tests__/testUtils.js
- src/replicator.js
This PR adds support for passing an IdentityWallet instance to `openBox`. 
This functionality still needs some integration tests to make sure that all IdentityWallet functionality works as intended.
> feat: openBox now works with IdentityWallet instance

- package-lock.json
- package.json
- src/3box.js
- src/keyValueStore.js
- src/thread.js
> Greenkeeper/standard 14.3.1

- src/config.js
> GhostThread: added prod signalling servers

- src/__tests__/ghost.test.js
- src/ghost.js
- src/space.js
This PR got rid of the other bad commits, should be all clear as well.
> GhostThread: Backlog limit added

- .npmignore
- package-lock.json
- package.json
- src/3box.js
- src/3id/__tests__/3id.test.js
- src/3id/__tests__/__snapshots__/3id.test.js.snap
- src/3id/index.js
- src/__mocks__/3ID.js
- src/__tests__/idWallet.integration.js
- src/replicator.js
- src/utils/index.js
First go at 3id provider support.
> feat: support for 3ID Provider

- src/3box.js
Fix for running 3box in node.js
> fix(3box): check for window correctly in initIPFSRepo

- package.json
Removed some dependencies that are not being used.
> fix(package): remove unused dependencies

- package.json
- src/3box.js
- src/__tests__/replicator.test.js
- src/replicator.js
Disconnect form pinning room after we got all relevant responses or just published our DB.
> fix(replicator): disconnect from pinning room

- src/3box.js
- src/__tests__/idWallet.integration.js
> fix(3box): await promise to validate link

- src/3box.js
- src/3id/__tests__/3id.test.js
- src/3id/index.js
- src/__mocks__/3ID.js
- src/__mocks__/3box.js
- src/__tests__/3box.test.js
- src/__tests__/verified.test.js
- src/api.js
- src/ghost.js
- src/replicator.js
- src/utils/verifier.js
@oed already did all the hard work with recent refactors and work :)
~~just pushing up quickly, but need to double check things and probably fix some tests~~
> feat: 3id migration

- package.json
- src/utils/index.js
Check if Authereum and sign with admin key if so.
> fix(util): Special signature request for authereum

- example/index.html
- example/index.js
- package-lock.json
- package.json
- readme-template.md
- src/3id/index.js
- src/3id/keyring.js
- src/3id/utils.js
- src/__tests__/confThread.test.js
- src/__tests__/space.test.js
- src/__tests__/thread.test.js
- src/space.js
- src/thread.js
~~No need to review yet~~
~~Implementation sketch, works with first user, little bit of code need for add member/mode, some refactoring, some error handling/constraints and tests~~
> feat: confidential threads

- src/3box.js
- src/__tests__/replicator.test.js
- src/replicator.js
- webpack.dev.config.js
Merge the replicator's `start` and `new` functions.
> merge replicator's start and new methods

- .gitignore
- src/3box.js
- add option for specifying Ghost Pinbot address
> feat(3box): add option for specifying Ghost Pinbot address

- src/3box.js
- keep alive connection to the Ghost Pinbot
> Ghost Pinbot keep alive

- src/3box.js
- src/__tests__/ghost.test.js
- src/ghost.js
- src/space.js
- src/utils/index.js
- exclude Ghost Pinbot peer ID from members list
- implement unit test
- fix hanging issue with existing Ghost Thread tests
> Ghost Pinbot peer ID exclusion

- .gitignore
- RELEASE-NOTES.md
- package-lock.json
- package.json
Simply bump libp2p-pubsub to 0.4.6
> Fix/update libp2p pubsub (Release 1.20.1)

- src/3box.js
Better output of error message in the `openSpace` method.
> fix: better error message on openSpace

- package-lock.json
- package.json
- src/3box.js
- src/config.js
- src/replicator.js
will run locally after iframe release
> feat: iframe shared ipfs and orbitdb cache/repo
