3box/3box-js

- src/keyValueStore.js
Adds timestamps to set data. Keeps for internal use for now. We may want to add other additional internal metadata in the future, this starts using it as { value: 'val set by app', timestamp: ..., metadata1: ..., metadata2: ....}. While a get only returns value.  Maybe want to externalize in future.
> feat: add internal metadata to sets, timestamp

- src/__tests__/keyValueStore.test.js
- src/keyValueStore.js
One problem related to this PR and the timestamp one is that remove or DEL events don't have timestamps, right not DEL events are still returned but with value null and timestamp null. Probably worth resolving after this.
> feat: make available time order log/history of store

- src/3box.js
We don't take any different action whether publishRootStore fails or succeeds at the moment, so remove await for now, since we don't need the output, and this speeds up opening
> feat: remove wait pub rs address

- src/3box.js
Did a bunch of experimentation for this one. Overall I decided to stick with the default ipfs bootstrap nodes as it's not much slower (~200ms) and allows us to connect to other browser nodes. It should also be less fragile to rely on ipfs defaults. 
Here we kept the configured bootstrap nodes in the ipfs options.
start ipfs: 763ms
start ipfs: 658ms
start ipfs: 720ms
start ipfs: 805ms
start ipfs: 691ms
Here we removed the bootstrap nodes from the ipfs options, note though that this configuration uses ipfs default bootstrap nodes instead.
start ipfs: 634ms
start ipfs: 648ms
start ipfs: 721ms
start ipfs: 653ms
start ipfs: 674ms
This option makes ipfs not use it's default bootstrap nodes.
start ipfs: 452ms
start ipfs: 477ms
start ipfs: 443ms
start ipfs: 420ms
start ipfs: 493ms
Uses only swarm …
> Removed configured bootstrap nodes

- package.json
XMLHttpRequest already does this, and it should be a sufficient hint for any bundler to not include the node modules, but it is not working for a number of people. This makes it more explicit, by specifying the same in our own package.
> build: package bundler hint to excluded node modules

- src/3box.js
This way we're not making any assumptions about whether the addresses have been checksummed or not.
This is backwards-compatible with existing profiles created using 3box-dapp, as the addresses being used are already lower-cased.
Resolves #169
> Always lower-case ethereum addresses that are function inputs

- src/3box.js
Also connect to pinning node for getProfile. libp2p discovery nodes were throwing some errors the last few days, so lib could not find our ipfs node and sync the data.
> fix: connect to pin node directly, libp2p discovery servers not needed

- CONTRIBUTING.md
Add doc linking to the contributor guide in the main 3box repo.
> Add doc linking to contribution guide

- src/utils.js
Turns out XMLHttpRequest only returns `responseText` while browsers return both that and `response`.
> Fixed bug in getProfile when running node

- src/3box.js
- src/__tests__/3box.test.js
The _linkProfile method was the only one that really needed updating. Now it only stores the link to localstorage if the call is successful.
> Handle _linkProfile errors correctly

- src/3box.js
Likely the solution to https://github.com/3box/3box-js/issues/203. 203 shouldn't really be issue and it likely an issue in ipfs/libp2p2, it looks like that when its trying to connect it fails, it keeps trying and runs out memory causing it to fail or the error is block something. But anyways bootstrap nodes not necessary right now, we know a node to connect to.
> fix: libp2p/ipfs boostrap node option

- README.md
- package.json
- readme-template.md
- src/3box.js
- src/__tests__/3box.test.js
Didn't add an explicity function to make the profile public. Instead I stored the proof for the ethereum address in the public store. This should reduce the number of times the linkProfile consent message is shown to only once (before you'd have to do it every time you cleared your cache).
> Store link consent (proof for ethereum address) in public store

- package.json
This makes sure that there aren't any old files included in new builds.
cc @sethfork
> Fix: Clean ES5 build

- src/3box.js
Fixes bug where no opts object is passed to openBox.
> Not passsing opts to openBox no longer breaks

- src/3box.js
- src/__tests__/3box.test.js
- src/keyValueStore.js
- src/space.js
Implemented with minimal code diff, but this was also a good area for refactor. We should have two additional logical services, one that handles pubsub messages, on peers joining, and more importantly messages on response now that it is not only relevant to openbox, but also spaces, and they happen at differing times. Second we could probably have a logical service that handles syncing state across dbs/spaces. 
In the current implementation the pinDB message to the pinning server results in the pinning server opening all stores, including all spaces. We will likely want to change to this to open what is needed when it is needed.
We could also refactor some the code around open/load/sync as similar handling is need for both primary DBs and spaces, but code exist in two different places at …
> feat: onsync done for spaces

- src/3box.js
- src/api.js
- src/utils/index.js
> fix: throw during fetch & return empty profile

- readme-template.md
Fix key conventions link because the old file was removed.
> Fix key conventions link

- example/index.html
- example/index.js
- src/3box.js
- src/__tests__/space.test.js
- src/__tests__/testUtils.js
- src/__tests__/thread.test.js
- src/space.js
- src/thread.js
This is still a WIP but should work quite well already. There is a new `Thread` class. Instances of this class can be created using the Space api. 
Since threads are not added to the users rootstore we need a new way to announce the thread to the pinning node. To do this the new `SYNC_DB` message is used according to our updated pinning node spec. Note that this requires an update to our pinning node in order to function properly
> feat(space): Implemented simple threads

- src/3box.js
- src/__tests__/3box.test.js
- src/api.js
- src/utils/index.js
> Allow Muport DIDs (in the cached version)

- src/3box.js
- src/__tests__/3box.test.js
> Update link profile logic

- src/3box.js
This sends along the DID of the user to the pinning network so that it can be persisted.
> Feat(network): Send did to pinning node on PIN_DB

- src/3box.js
Looks like we where silently eating up the error thrown by MetaMask if the user denies consent. This should be fixed with this PR.
> fix(spaces): Don't silently fail if user denies consent.

- src/__tests__/keyValueStore.test.js
- src/keyValueStore.js
> fix: use seconds timestamps in metadata

- src/__tests__/keyValueStore.test.js
- src/__tests__/privateStore.test.js
- src/__tests__/publicStore.test.js
- src/__tests__/space.test.js
- src/keyValueStore.js
- src/privateStore.js
- src/publicStore.js
- src/space.js
- src/utils/index.js
Fixes #401 
This PR adds a check to all `set` and `remove` methods that throws an error if `key` is not defined.
> fix(spaces): Throw error if key is not defined

- package.json
- src/3box.js
- src/3id/__tests__/keyring.test.js
- src/3id/keyring.js
- src/__tests__/3box.test.js
- src/__tests__/keyValueStore.test.js
- src/__tests__/testUtils.js
- src/__tests__/thread.test.js
- src/keyValueStore.js
- src/thread.js
Sometimes we get a different version of elliptic than orbit-db-keystore which causes issues since it thinks that a ec key instance is some other object. This PR fixes this by using orbit-db-keystore directly.
> fix(3id): Use orbit-db-keystore to import private key in correct format

- src/3box.js
- src/api.js
This PR adds a simple blocklist function that can be passed to `getProfile` and `getSpace`. This function accepts an address and should return a boolean. If true the `get` functions will throw an error saying the user is blocked.
> feat(api): add blocklist to getProfile and getSpace

- README.md
- example/index.html
- example/index.js
- package.json
- src/3box.js
- src/__mocks__/3ID.js
- src/__tests__/3box.test.js
- src/__tests__/__snapshots__/3box.test.js.snap
- src/__tests__/keyValueStore.test.js
- src/__tests__/space.test.js
- src/__tests__/thread.test.js
- src/api.js
- src/space.js
- src/thread.js
rodMod -> firstModerator
membersOnly -> members 
space._activeThreads by address instead of name 
refactor 3id mock for tests, old keyvalue store did mock failed, 3box test still failing, need to update
> ref: api changes, joinThreadByAddress, keep active threads by address

- src/3box.js
- src/3id/__tests__/3id.test.js
- src/3id/__tests__/__snapshots__/3id.test.js.snap
- src/3id/index.js
Resolves https://github.com/3box/3box-js/issues/528
This PR adds a contentSignature option to the `getIdFromEthAddress` method in `3id.js`
This can enable wallets to provide signatures for authorizing 3box as an option when creating a new 3box instance, thereby removing the need for user action to confirm the signature.
The PR also updates documentation for `openBox` in `3box.js` and adds unit tests to cover the new functionality of `getIdFromEthAddress`
> Adds contentSignature option to getIdFromEthAddress

- src/3box.js
Simply just add a call to verify signature of proof and wrap it in the catch block. This will prevent errors by developers adding an invalid proof, which might break a users 3box.
> feat: verify proof if given to linkAddress method

- src/3id/index.js
If the provider is metamask we don't have to send the rpc request asking for 3ID rpc support.
> feat: check if provider is metamask in has3idSupport

- src/utils/index.js
Without the second parameter infura `Geth/v1.8.27-omnibus-c94f741c/linux-amd64/go1.11.1` returns an error:
```
"code": -32602,
"message": "missing value for required argument 1"
```
Parity seems to have no problem with the missing parameter.
> Bugfix: eth_getCode add second parameter "latest"

- README.md
- src/3box.js
- src/api.js
This PR makes the `api.js` module in to a class called `BoxApi`. The main `Box` class of `3box.js` now extends this class. This makes the code in `3box.js` less cluttered.
> ref(api): move static api functions to separate class

- package-lock.json
- package.json
- src/__tests__/ghost.test.js
- src/ghost.js
Main consideration here is that not posts are actually saved as ipfs objects. I considered just calculating the hash of the object and not storing it locally. However, this might cause confusion if anyone tries to fetch a post using the postId. This should be handled by the ipfs GC in the future.
Also removed the errors from the ghost tests :)
> fix(ghost): add postId to ghost posts

- src/3id/index.js
Fixes an issue that arose when using IDW in browser and 3Box was using `isAuthenticated` to get check if the space session had been initiated. See here for more details: https://github.com/3box/identity-wallet-js/issues/26
> fix(3id): Open space correctly when using IDW in browser

- example/index.html
- example/index.js
- package-lock.json
- package.json
- src/3box.js
- src/ghost.js
- src/space.js
This fixes a bug where ghost threads don't work when you're not autenticated.
From discord:
Kenzo - 3BoxToday at 12:57 AM
@oed 3⃣ 
Now Im able to openThread which is really cool but there seem to be a few issues. The returned thread from openThread should be the same as the thread that was returned the original way via joinThread correct?
Im doing 
const box = await Box.create(ethereum);
const thread = await box.openThread(spaceName, threadName, { ghost: true });
this.setState({ thread, threadJoined: true, }, async () => {
await this.updateComments();
await this.updateMembersOnline();
thread.onUpdate(() => this.updateComments());
thread.onNewCapabilities(() => this.updateMembersOnline());
});
which is exactly how I was fetching comments the original way, though now it doesnt return any …
> fix(ghost): fixed bug when opening ghost thread while not authenticated

- src/utils/verifier.js
Fixes bug where if you had a muport DID in your 3ID verification the `Box.getVerifiedAccounts` broke.
> fix(verifier): Verify legacy muport DID properly

- src/utils/index.js
The signing key is a persistent key dedicated to message signing which will have less privileges than the admin key since admin key. This also avoids the popup window for signing messages.
> Use authereum signing key

- src/3box.js
- src/__tests__/3box.test.js
- src/__tests__/__snapshots__/3box.test.js.snap
- src/__tests__/publicStore.test.js
- src/publicStore.js
This PR improves UX by prompting the user to sign the account link message when authenticating if it has not already happened. Before this only happened once you opened a space or added data to the public store. 
This makes the code cleaner and easier to work with while improving stability.
> ref: link address directly on auth

- package-lock.json
This Just bumps the `libp2p-webrtc-star` dependency to suppress connection errors: https://github.com/libp2p/js-libp2p/issues/662#event-3433003905
> chore: bump libp2p-webrtc-star

- package-lock.json
- package.json
- src/replicator.js
Fix allowed one my oldest accounts to work again (from Oct 2018). One of the address-links in rootstore had a cid which was not available anywhere (ie our pinning node). This may have occurred from number of things, from switching to storing links in rootstore/ipfs, to not pinning links at one point on pinning node (i think this was bug at one point...), etc I did have a second existing link that was valid and resolved (but the other blocked this before fix). This also blocked creating new link, if an old one was not able to resolve.
> fix: timeout links which dont resolve ipfs.dag.get

- package.json
- src/3box.js
Makes sure the linked rootstore address has the correct format.
> fix: ensure correct rootstore address
